version: '3.7'
services:
  cicd:
    build: .
    environment:
      - AWS_PROFILE=${AWS_PROFILE-default}
      - STAGE_ENV=${STAGE_ENV-development}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION-us-east-1}
      - SAM_CLI_TELEMETRY=0
      - DIDPWD=${PWD}
    volumes:
      - ~/.aws:/root/.aws:delegated
      - .:/var/task:delegated
      - /var/run/docker.sock:/var/run/docker.sock
