name: CI/CD
on: [push]
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure AWS
        run: |
          echo "::set-env name=AWS_ACCESS_KEY_ID::${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "::set-env name=AWS_SECRET_ACCESS_KEY::${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "::set-env name=AWS_DEFAULT_REGION::us-east-1"
      - name: Bootstrap
        run: |
          ./bin/bootstrap
      - name: Setup
        run: |
          ./bin/setup
      - name: Test
        run: |
          ./bin/test
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          ./bin/deploy-cicd
